### PR TITLE
Corrected sorting of routes #121

### PR DESCRIPTION
**Pull request by m42e**
PR for #121

### CODE REVIEW

**Comment by m42e** [comment]
@kpande here it is

**Comment by m42e** [comment]
@augustohp Can you hava a look at the Scrutinizer, I've fixed the method to match the test results.

**Comment by NeroMorto** [comment]
This PR also required for correct work on PHP >= 7. Because there is a difference in usort callback function that used in sortRoutesByComplexity method.
Is it possible to approve it and merge into master?

**Comment by nickl-** [comment]
Not sure why scrutiniser has an issue with this. Don't feel confident enough that everything is on he up and up.

**Comment by nickl-** [comment]
Closed: fixed sorting at 72cde63b78143b706011ed2e54c581705f107b71

**Pull request closed without merging**
